// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261001114915_InitialCreateDatabase")]
    partial class InitialCreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Mỹ phẩm Skincare",
                            Description = "Kem dưỡng, serum, toner, sữa rửa mặt chính hãng"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Trang điểm (Makeup)",
                            Description = "Son môi, phấn nước, kẻ mắt, má hồng"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Mặt nạ dưỡng da",
                            Description = "Mặt nạ giấy, mặt nạ ngủ, mặt nạ đất sét"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Chăm sóc tóc & Da đầu",
                            Description = "Dầu gội, dầu xả, ủ tóc, serum dưỡng tóc"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Chăm sóc cơ thể",
                            Description = "Sữa tắm, dưỡng thể, tẩy tế bào chết body"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Nước hoa chính hãng",
                            Description = "Nước hoa mini, fullsize, body mist lưu hương"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Thực phẩm chức năng làm đẹp",
                            Description = "Viên uống collagen, vitamin C, trắng da, chống lão hóa"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Chăm sóc da tay & chân",
                            Description = "Kem dưỡng da tay, mặt nạ chân, trị nứt nẻ"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Dụng cụ & Phụ kiện trang điểm",
                            Description = "Cọ trang điểm, bông mút, kẹp bấm mi, gương mini"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Chăm sóc răng miệng",
                            Description = "Kem đánh răng trắng răng, nước súc miệng, bàn chải"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Sản phẩm cho nam giới",
                            Description = "Sữa rửa mặt nam, sáp vuốt tóc, bọt cạo râu"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Chăm sóc mẹ & bé",
                            Description = "Sữa tắm gội em bé, kem chống hăm, dưỡng ẩm da bé"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Chống nắng & Bảo vệ da",
                            Description = "Kem chống nắng mặt, chống nắng body, xịt chống nắng"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Sản phẩm trị mụn & Thâm",
                            Description = "Gel chấm mụn, serum trị thâm, miếng dán mụn"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Tẩy trang & Làm sạch sâu",
                            Description = "Nước tẩy trang, dầu tẩy trang, sáp tẩy trang"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Tinh dầu & Thư giãn",
                            Description = "Tinh dầu dưỡng da, nến thơm, xịt thơm phòng ngủ"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Tóc giả & Phụ kiện tóc",
                            Description = "Kẹp tóc, dây buộc tóc hàn quốc, lược gỡ rối"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Mỹ phẩm mini & Travel size",
                            Description = "Set mini dùng thử, tuýp nhỏ tiện lợi mang đi du lịch"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Hộp đựng & Tổ chức mỹ phẩm",
                            Description = "Tủ đựng mỹ phẩm trong suốt, túi đựng đồ trang điểm"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Quà tặng & Set mỹ phẩm",
                            Description = "Hộp quà sinh nhật, set quà lễ hội, túi giấy Hana Shop"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8809123456011",
                            CategoryId = 1,
                            Price = 850000m,
                            ProductName = "Serum dưỡng ẩm La Roche-Posay Hyalu B5 30ml",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8809123456012",
                            CategoryId = 2,
                            Price = 180000m,
                            ProductName = "Son kem lì Romand Blur Fudge Tint",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8809123456013",
                            CategoryId = 3,
                            Price = 25000m,
                            ProductName = "Mặt nạ giấy Mediheal Teatree Care Solution Essential",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8809123456014",
                            CategoryId = 4,
                            Price = 780000m,
                            ProductName = "Tinh dầu dưỡng tóc Moroccanoil Treatment 100ml",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8809123456015",
                            CategoryId = 5,
                            Price = 175000m,
                            ProductName = "Sữa tắm hương nước hoa On The Body Hàn Quốc 500g",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8809123456016",
                            CategoryId = 6,
                            Price = 320000m,
                            ProductName = "Xịt thơm toàn thân Body Mist Bath & Body Works 236ml",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8809123456017",
                            CategoryId = 7,
                            Price = 650000m,
                            ProductName = "Viên uống Collagen dạng nước InnerB Aqua Rich",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8809123456018",
                            CategoryId = 8,
                            Price = 95000m,
                            ProductName = "Kem dưỡng da tay, chống khô nẻ Kamill 75ml",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8809123456019",
                            CategoryId = 9,
                            Price = 380000m,
                            ProductName = "Bộ cọ trang điểm cá nhân Real Techniques 4 món",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8809123456020",
                            CategoryId = 10,
                            Price = 190000m,
                            ProductName = "Kem đánh răng Marvis Classic Strong Mint 85ml",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8809123456021",
                            CategoryId = 11,
                            Price = 185000m,
                            ProductName = "Sáp vuốt tóc nam giữ nếp cao Gatsby Moving Rubber",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8809123456022",
                            CategoryId = 12,
                            Price = 240000m,
                            ProductName = "Sữa tắm gội toàn thân Cetaphil Baby 400ml",
                            StockQuantity = 28
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8809123456023",
                            CategoryId = 13,
                            Price = 520000m,
                            ProductName = "Kem chống nắng nâng tông Anessa Sun Care Milk 60ml",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8809123456024",
                            CategoryId = 14,
                            Price = 380000m,
                            ProductName = "Gel giảm mụn cấp tốc chuyên sâu La Roche-Posay Effaclar AI",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8809123456025",
                            CategoryId = 15,
                            Price = 420000m,
                            ProductName = "Nước tẩy trang Bioderma Sensibio H2O 500ml",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "8809123456026",
                            CategoryId = 16,
                            Price = 350000m,
                            ProductName = "Nến thơm phòng hương hoa nhài Yankee Candle",
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "8809123456027",
                            CategoryId = 17,
                            Price = 340000m,
                            ProductName = "Lược gỡ rối chuyên nghiệp Tangle Teezer Original",
                            StockQuantity = 22
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "8809123456028",
                            CategoryId = 18,
                            Price = 450000m,
                            ProductName = "Set dưỡng da mini 4 món Laneige Essential Power",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "8809123456029",
                            CategoryId = 19,
                            Price = 150000m,
                            ProductName = "Hộp đựng mỹ phẩm trong suốt nhiều ngăn để bàn",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "8809123456030",
                            CategoryId = 20,
                            Price = 590000m,
                            ProductName = "Set hộp quà mỹ phẩm xách tay cao cấp Hana Shop",
                            StockQuantity = 10
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
