// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008111439_PassWord")]
    partial class PassWord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Mỹ phẩm Skincare",
                            Description = "Kem dưỡng, serum, toner, sữa rửa mặt chính hãng"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Trang điểm (Makeup)",
                            Description = "Son môi, phấn nước, kẻ mắt, má hồng"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Mặt nạ dưỡng da",
                            Description = "Mặt nạ giấy, mặt nạ ngủ, mặt nạ đất sét"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Chăm sóc tóc & Da đầu",
                            Description = "Dầu gội, dầu xả, ủ tóc, serum dưỡng tóc"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Chăm sóc cơ thể",
                            Description = "Sữa tắm, dưỡng thể, tẩy tế bào chết body"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Nước hoa chính hãng",
                            Description = "Nước hoa mini, fullsize, body mist lưu hương"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Thực phẩm chức năng làm đẹp",
                            Description = "Viên uống collagen, vitamin C, trắng da, chống lão hóa"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Chăm sóc da tay & chân",
                            Description = "Kem dưỡng da tay, mặt nạ chân, trị nứt nẻ"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Dụng cụ & Phụ kiện trang điểm",
                            Description = "Cọ trang điểm, bông mút, kẹp bấm mi, gương mini"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Chăm sóc răng miệng",
                            Description = "Kem đánh răng trắng răng, nước súc miệng, bàn chải"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Sản phẩm cho nam giới",
                            Description = "Sữa rửa mặt nam, sáp vuốt tóc, bọt cạo râu"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Chăm sóc mẹ & bé",
                            Description = "Sữa tắm gội em bé, kem chống hăm, dưỡng ẩm da bé"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Chống nắng & Bảo vệ da",
                            Description = "Kem chống nắng mặt, chống nắng body, xịt chống nắng"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Sản phẩm trị mụn & Thâm",
                            Description = "Gel chấm mụn, serum trị thâm, miếng dán mụn"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Tẩy trang & Làm sạch sâu",
                            Description = "Nước tẩy trang, dầu tẩy trang, sáp tẩy trang"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Tinh dầu & Thư giãn",
                            Description = "Tinh dầu dưỡng da, nến thơm, xịt thơm phòng ngủ"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Tóc giả & Phụ kiện tóc",
                            Description = "Kẹp tóc, dây buộc tóc hàn quốc, lược gỡ rối"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Mỹ phẩm mini & Travel size",
                            Description = "Set mini dùng thử, tuýp nhỏ tiện lợi mang đi du lịch"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Hộp đựng & Tổ chức mỹ phẩm",
                            Description = "Tủ đựng mỹ phẩm trong suốt, túi đựng đồ trang điểm"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Quà tặng & Set mỹ phẩm",
                            Description = "Hộp quà sinh nhật, set quà lễ hội, túi giấy Hana Shop"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Đường Nguyễn Trãi, Phường 2, Quận 5, Thành phố Hồ Chí Minh",
                            CustomerName = "Nguyễn Thị Hoa",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "45 Đường Lê Văn Việt, Phường Hiệp Phú, Thành phố Thủ Đức, Thành phố Hồ Chí Minh",
                            CustomerName = "Trần Thị Mai",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0982233445",
                            RewardPoints = 80
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "88 Đường Đồng Khởi, Phường Bến Nghé, Quận 1, Thành phố Hồ Chí Minh",
                            CustomerName = "Lê Hoàng Yến",
                            MembershipRank = "Kim cương",
                            PhoneNumber = "0913344556",
                            RewardPoints = 1200
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "12 Đường Cách Mạng Tháng Tám, Phường 7, Quận Tân Bình, Thành phố Hồ Chí Minh",
                            CustomerName = "Phạm Quỳnh Anh",
                            MembershipRank = "Thành viên mới",
                            PhoneNumber = "0394455667",
                            RewardPoints = 20
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "56 Đường Võ Văn Ngân, Phường Linh Chiểu, Thành phố Thủ Đức, Thành phố Hồ Chí Minh",
                            CustomerName = "Hoàng Thu Thảo",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0975566778",
                            RewardPoints = 320
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "99 Đường Phan Xích Long, Phường 2, Quận Phú Nhuận, Thành phố Hồ Chí Minh",
                            CustomerName = "Vũ Minh Thư",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0936677889",
                            RewardPoints = 95
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "234 Đường Hai Bà Trưng, Phường Võ Thị Sáu, Quận 3, Thành phố Hồ Chí Minh",
                            CustomerName = "Đặng Ngọc Hân",
                            MembershipRank = "Kim cương",
                            PhoneNumber = "0927788990",
                            RewardPoints = 950
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "15 Đường Nguyễn Kiệm, Phường 3, Quận Gò Vấp, Thành phố Hồ Chí Minh",
                            CustomerName = "Bùi Thanh Trúc",
                            MembershipRank = "Thành viên mới",
                            PhoneNumber = "0868899001",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "78 Đường Lê Duẩn, Phường Bến Nghé, Quận 1, Thành phố Hồ Chí Minh",
                            CustomerName = "Đỗ Mỹ Linh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0949900112",
                            RewardPoints = 450
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "300 Đường Nguyễn Thị Minh Khai, Phường 5, Quận 3, Thành phố Hồ Chí Minh",
                            CustomerName = "Hồ Ngọc Hà",
                            MembershipRank = "Kim cương",
                            PhoneNumber = "0901011223",
                            RewardPoints = 1500
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "11 Đường Tôn Đức Thắng, Phường Bến Nghé, Quận 1, Thành phố Hồ Chí Minh",
                            CustomerName = "Ngô Thanh Vân",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0982122334",
                            RewardPoints = 110
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "50 Đường Hoàng Văn Thụ, Phường 15, Quận Phú Nhuận, Thành phố Hồ Chí Minh",
                            CustomerName = "Dương Cẩm Lynh",
                            MembershipRank = "Thành viên mới",
                            PhoneNumber = "0913233445",
                            RewardPoints = 35
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "77 Đường Thảo Điền, Phường Thảo Điền, Thành phố Thủ Đức, Thành phố Hồ Chí Minh",
                            CustomerName = "Lý Nhã Kỳ",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0394344556",
                            RewardPoints = 280
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "102 Đường Pasteur, Phường Bến Nghé, Quận 1, Thành phố Hồ Chí Minh",
                            CustomerName = "Trương Ngọc Ánh",
                            MembershipRank = "Kim cương",
                            PhoneNumber = "0975455667",
                            RewardPoints = 1100
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "45 Đường Thành Thái, Phường 14, Quận 10, Thành phố Hồ Chí Minh",
                            CustomerName = "Phan Như Thảo",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0936566778",
                            RewardPoints = 75
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "89 Đường Lũy Bán Bích, Phường Tân Thới Hòa, Quận Tân Phú, Thành phố Hồ Chí Minh",
                            CustomerName = "Vương Linh Chi",
                            MembershipRank = "Thành viên mới",
                            PhoneNumber = "0927677889",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "210 Đường Điện Biên Phủ, Phường 17, Quận Bình Thạnh, Thành phố Hồ Chí Minh",
                            CustomerName = "Đinh Ngọc Diệp",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0868788990",
                            RewardPoints = 510
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "66 Đường Quang Trung, Phường 10, Quận Gò Vấp, Thành phố Hồ Chí Minh",
                            CustomerName = "Cao Thái Sơn",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0948900112",
                            RewardPoints = 60
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "33 Đường Sư Vạn Hạnh, Phường 12, Quận 10, Thành phố Hồ Chí Minh",
                            CustomerName = "Trịnh Thăng Bình",
                            MembershipRank = "Thành viên mới",
                            PhoneNumber = "0909011223",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "1 Công Trường Lam Sơn, Phường Bến Nghé, Quận 1, Thành phố Hồ Chí Minh",
                            CustomerName = "Sơn Tùng M-TP",
                            MembershipRank = "Kim cương",
                            PhoneNumber = "0989122334",
                            RewardPoints = 2000
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CashierUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CashierUsername = "cashier01",
                            CreatedDate = new DateTime(2026, 3, 1, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            FinalAmount = 1030000m,
                            OrderCode = "HD-20260301-001",
                            RewardPoints = 10,
                            TotalItems = 2
                        },
                        new
                        {
                            OrderId = 2,
                            CashierUsername = "cashier02",
                            CreatedDate = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            FinalAmount = 780000m,
                            OrderCode = "HD-20260301-002",
                            RewardPoints = 7,
                            TotalItems = 1
                        },
                        new
                        {
                            OrderId = 3,
                            CashierUsername = "cashier01",
                            CreatedDate = new DateTime(2026, 3, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            FinalAmount = 980000m,
                            OrderCode = "HD-20260302-001",
                            RewardPoints = 9,
                            TotalItems = 3
                        },
                        new
                        {
                            OrderId = 4,
                            CashierUsername = "cashier03",
                            CreatedDate = new DateTime(2026, 3, 2, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            FinalAmount = 95000m,
                            OrderCode = "HD-20260302-002",
                            RewardPoints = 1,
                            TotalItems = 1
                        },
                        new
                        {
                            OrderId = 5,
                            CashierUsername = "cashier02",
                            CreatedDate = new DateTime(2026, 3, 3, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            FinalAmount = 570000m,
                            OrderCode = "HD-20260303-001",
                            RewardPoints = 5,
                            TotalItems = 2
                        },
                        new
                        {
                            OrderId = 6,
                            CashierUsername = "cashier04",
                            CreatedDate = new DateTime(2026, 3, 3, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 6,
                            FinalAmount = 185000m,
                            OrderCode = "HD-20260303-002",
                            RewardPoints = 1,
                            TotalItems = 1
                        },
                        new
                        {
                            OrderId = 7,
                            CashierUsername = "cashier01",
                            CreatedDate = new DateTime(2026, 3, 4, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 7,
                            FinalAmount = 760000m,
                            OrderCode = "HD-20260304-001",
                            RewardPoints = 7,
                            TotalItems = 2
                        },
                        new
                        {
                            OrderId = 8,
                            CashierUsername = "cashier05",
                            CreatedDate = new DateTime(2026, 3, 4, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 8,
                            FinalAmount = 420000m,
                            OrderCode = "HD-20260304-002",
                            RewardPoints = 4,
                            TotalItems = 1
                        },
                        new
                        {
                            OrderId = 9,
                            CashierUsername = "cashier03",
                            CreatedDate = new DateTime(2026, 3, 5, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 9,
                            FinalAmount = 690000m,
                            OrderCode = "HD-20260305-001",
                            RewardPoints = 6,
                            TotalItems = 2
                        },
                        new
                        {
                            OrderId = 10,
                            CashierUsername = "cashier02",
                            CreatedDate = new DateTime(2026, 3, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 10,
                            FinalAmount = 450000m,
                            OrderCode = "HD-20260305-002",
                            RewardPoints = 4,
                            TotalItems = 1
                        },
                        new
                        {
                            OrderId = 11,
                            CashierUsername = "cashier06",
                            CreatedDate = new DateTime(2026, 3, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 11,
                            FinalAmount = 740000m,
                            OrderCode = "HD-20260306-001",
                            RewardPoints = 7,
                            TotalItems = 2
                        },
                        new
                        {
                            OrderId = 12,
                            CashierUsername = "cashier01",
                            CreatedDate = new DateTime(2026, 3, 6, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 12,
                            FinalAmount = 590000m,
                            OrderCode = "HD-20260306-002",
                            RewardPoints = 5,
                            TotalItems = 1
                        },
                        new
                        {
                            OrderId = 13,
                            CashierUsername = "cashier04",
                            CreatedDate = new DateTime(2026, 3, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 13,
                            FinalAmount = 1030000m,
                            OrderCode = "HD-20260307-001",
                            RewardPoints = 10,
                            TotalItems = 2
                        },
                        new
                        {
                            OrderId = 14,
                            CashierUsername = "cashier05",
                            CreatedDate = new DateTime(2026, 3, 7, 18, 25, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 14,
                            FinalAmount = 250000m,
                            OrderCode = "HD-20260307-002",
                            RewardPoints = 2,
                            TotalItems = 1
                        },
                        new
                        {
                            OrderId = 15,
                            CashierUsername = "cashier02",
                            CreatedDate = new DateTime(2026, 3, 8, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 15,
                            FinalAmount = 1095000m,
                            OrderCode = "HD-20260308-001",
                            RewardPoints = 10,
                            TotalItems = 3
                        },
                        new
                        {
                            OrderId = 16,
                            CashierUsername = "cashier03",
                            CreatedDate = new DateTime(2026, 3, 8, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 16,
                            FinalAmount = 320000m,
                            OrderCode = "HD-20260308-002",
                            RewardPoints = 3,
                            TotalItems = 1
                        },
                        new
                        {
                            OrderId = 17,
                            CashierUsername = "cashier06",
                            CreatedDate = new DateTime(2026, 3, 9, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 17,
                            FinalAmount = 840000m,
                            OrderCode = "HD-20260309-001",
                            RewardPoints = 8,
                            TotalItems = 2
                        },
                        new
                        {
                            OrderId = 18,
                            CashierUsername = "cashier01",
                            CreatedDate = new DateTime(2026, 3, 9, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 18,
                            FinalAmount = 190000m,
                            OrderCode = "HD-20260309-002",
                            RewardPoints = 1,
                            TotalItems = 1
                        },
                        new
                        {
                            OrderId = 19,
                            CashierUsername = "cashier06",
                            CreatedDate = new DateTime(2026, 3, 10, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 19,
                            FinalAmount = 760000m,
                            OrderCode = "HD-20260310-001",
                            RewardPoints = 7,
                            TotalItems = 2
                        },
                        new
                        {
                            OrderId = 20,
                            CashierUsername = "cashier02",
                            CreatedDate = new DateTime(2026, 3, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 20,
                            FinalAmount = 520000m,
                            OrderCode = "HD-20260310-002",
                            RewardPoints = 5,
                            TotalItems = 1
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            LineTotal = 850000m,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 850000m
                        },
                        new
                        {
                            OrderDetailId = 2,
                            LineTotal = 180000m,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 180000m
                        },
                        new
                        {
                            OrderDetailId = 3,
                            LineTotal = 780000m,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 780000m
                        },
                        new
                        {
                            OrderDetailId = 4,
                            LineTotal = 50000m,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 2,
                            UnitPrice = 25000m
                        },
                        new
                        {
                            OrderDetailId = 5,
                            LineTotal = 650000m,
                            OrderId = 3,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 650000m
                        },
                        new
                        {
                            OrderDetailId = 6,
                            LineTotal = 190000m,
                            OrderId = 3,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 190000m
                        },
                        new
                        {
                            OrderDetailId = 7,
                            LineTotal = 95000m,
                            OrderId = 4,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 95000m
                        },
                        new
                        {
                            OrderDetailId = 8,
                            LineTotal = 175000m,
                            OrderId = 5,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 175000m
                        },
                        new
                        {
                            OrderDetailId = 9,
                            LineTotal = 380000m,
                            OrderId = 5,
                            ProductId = 14,
                            Quantity = 1,
                            UnitPrice = 380000m
                        },
                        new
                        {
                            OrderDetailId = 10,
                            LineTotal = 185000m,
                            OrderId = 6,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 185000m
                        },
                        new
                        {
                            OrderDetailId = 11,
                            LineTotal = 760000m,
                            OrderId = 7,
                            ProductId = 9,
                            Quantity = 2,
                            UnitPrice = 380000m
                        },
                        new
                        {
                            OrderDetailId = 12,
                            LineTotal = 420000m,
                            OrderId = 8,
                            ProductId = 15,
                            Quantity = 1,
                            UnitPrice = 420000m
                        },
                        new
                        {
                            OrderDetailId = 13,
                            LineTotal = 340000m,
                            OrderId = 9,
                            ProductId = 17,
                            Quantity = 1,
                            UnitPrice = 340000m
                        },
                        new
                        {
                            OrderDetailId = 14,
                            LineTotal = 350000m,
                            OrderId = 9,
                            ProductId = 16,
                            Quantity = 1,
                            UnitPrice = 350000m
                        },
                        new
                        {
                            OrderDetailId = 15,
                            LineTotal = 450000m,
                            OrderId = 10,
                            ProductId = 18,
                            Quantity = 1,
                            UnitPrice = 450000m
                        },
                        new
                        {
                            OrderDetailId = 16,
                            LineTotal = 240000m,
                            OrderId = 11,
                            ProductId = 12,
                            Quantity = 1,
                            UnitPrice = 240000m
                        },
                        new
                        {
                            OrderDetailId = 17,
                            LineTotal = 520000m,
                            OrderId = 11,
                            ProductId = 13,
                            Quantity = 1,
                            UnitPrice = 520000m
                        },
                        new
                        {
                            OrderDetailId = 18,
                            LineTotal = 590000m,
                            OrderId = 12,
                            ProductId = 20,
                            Quantity = 1,
                            UnitPrice = 590000m
                        },
                        new
                        {
                            OrderDetailId = 19,
                            LineTotal = 850000m,
                            OrderId = 13,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 850000m
                        },
                        new
                        {
                            OrderDetailId = 20,
                            LineTotal = 180000m,
                            OrderId = 13,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 180000m
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8809123456011",
                            CategoryId = 1,
                            Price = 850000m,
                            ProductName = "Serum dưỡng ẩm La Roche-Posay Hyalu B5 30ml",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8809123456012",
                            CategoryId = 2,
                            Price = 180000m,
                            ProductName = "Son kem lì Romand Blur Fudge Tint",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8809123456013",
                            CategoryId = 3,
                            Price = 25000m,
                            ProductName = "Mặt nạ giấy Mediheal Teatree Care Solution Essential",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8809123456014",
                            CategoryId = 4,
                            Price = 780000m,
                            ProductName = "Tinh dầu dưỡng tóc Moroccanoil Treatment 100ml",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8809123456015",
                            CategoryId = 5,
                            Price = 175000m,
                            ProductName = "Sữa tắm hương nước hoa On The Body Hàn Quốc 500g",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8809123456016",
                            CategoryId = 6,
                            Price = 320000m,
                            ProductName = "Xịt thơm toàn thân Body Mist Bath & Body Works 236ml",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8809123456017",
                            CategoryId = 7,
                            Price = 650000m,
                            ProductName = "Viên uống Collagen dạng nước InnerB Aqua Rich",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8809123456018",
                            CategoryId = 8,
                            Price = 95000m,
                            ProductName = "Kem dưỡng da tay, chống khô nẻ Kamill 75ml",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8809123456019",
                            CategoryId = 9,
                            Price = 380000m,
                            ProductName = "Bộ cọ trang điểm cá nhân Real Techniques 4 món",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8809123456020",
                            CategoryId = 10,
                            Price = 190000m,
                            ProductName = "Kem đánh răng Marvis Classic Strong Mint 85ml",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8809123456021",
                            CategoryId = 11,
                            Price = 185000m,
                            ProductName = "Sáp vuốt tóc nam giữ nếp cao Gatsby Moving Rubber",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8809123456022",
                            CategoryId = 12,
                            Price = 240000m,
                            ProductName = "Sữa tắm gội toàn thân Cetaphil Baby 400ml",
                            StockQuantity = 28
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8809123456023",
                            CategoryId = 13,
                            Price = 520000m,
                            ProductName = "Kem chống nắng nâng tông Anessa Sun Care Milk 60ml",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8809123456024",
                            CategoryId = 14,
                            Price = 380000m,
                            ProductName = "Gel giảm mụn cấp tốc chuyên sâu La Roche-Posay Effaclar AI",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8809123456025",
                            CategoryId = 15,
                            Price = 420000m,
                            ProductName = "Nước tẩy trang Bioderma Sensibio H2O 500ml",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "8809123456026",
                            CategoryId = 16,
                            Price = 350000m,
                            ProductName = "Nến thơm phòng hương hoa nhài Yankee Candle",
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "8809123456027",
                            CategoryId = 17,
                            Price = 340000m,
                            ProductName = "Lược gỡ rối chuyên nghiệp Tangle Teezer Original",
                            StockQuantity = 22
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "8809123456028",
                            CategoryId = 18,
                            Price = 450000m,
                            ProductName = "Set dưỡng da mini 4 món Laneige Essential Power",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "8809123456029",
                            CategoryId = 19,
                            Price = 150000m,
                            ProductName = "Hộp đựng mỹ phẩm trong suốt nhiều ngăn để bàn",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "8809123456030",
                            CategoryId = 20,
                            Price = 590000m,
                            ProductName = "Set hộp quà mỹ phẩm xách tay cao cấp Hana Shop",
                            StockQuantity = 10
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "Nguyễn Quản Trị",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "admin01"
                        },
                        new
                        {
                            UserId = 2,
                            FullName = "Trần Giám Đốc",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "admin02"
                        },
                        new
                        {
                            UserId = 3,
                            FullName = "Lê Thu Ngân",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Cashier",
                            Username = "cashier01"
                        },
                        new
                        {
                            UserId = 4,
                            FullName = "Phạm Bán Hàng",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Cashier",
                            Username = "cashier02"
                        },
                        new
                        {
                            UserId = 5,
                            FullName = "Hoàng Thu Ngân",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Cashier",
                            Username = "cashier03"
                        },
                        new
                        {
                            UserId = 6,
                            FullName = "Vũ Thị Quầy",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Cashier",
                            Username = "cashier04"
                        },
                        new
                        {
                            UserId = 7,
                            FullName = "Đỗ Bán Lẻ",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Cashier",
                            Username = "cashier05"
                        },
                        new
                        {
                            UserId = 8,
                            FullName = "Ngô Quản Kho",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Warehouse",
                            Username = "ware01"
                        },
                        new
                        {
                            UserId = 9,
                            FullName = "Bùi Kiểm Kê",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Warehouse",
                            Username = "ware02"
                        },
                        new
                        {
                            UserId = 10,
                            FullName = "Dương Thủ Kho",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Warehouse",
                            Username = "ware03"
                        },
                        new
                        {
                            UserId = 11,
                            FullName = "Lý Nhập Hàng",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Warehouse",
                            Username = "ware04"
                        },
                        new
                        {
                            UserId = 12,
                            FullName = "Đặng Hỗ Trợ",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "admin_backup"
                        },
                        new
                        {
                            UserId = 13,
                            FullName = "Hồ Ca Chiều",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Cashier",
                            Username = "cashier06"
                        },
                        new
                        {
                            UserId = 14,
                            FullName = "Trương Vận Chuyển",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Warehouse",
                            Username = "ware05"
                        },
                        new
                        {
                            UserId = 15,
                            FullName = "Mai Giám Sát",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "supervisor"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderDetail", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
